#cloud-config
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

packages:
  - nginx
package_update: true
runcmd:
  - [ systemctl, nginx-reload ]
  - [ systemctl, enable, nginx ]
  - [ systemctl, start, --no-block, nginx ]